package GUI;

import java.io.File;
import java.io.IOException;
import org.jrimum.bopepo.Boleto;
import org.jrimum.bopepo.view.BoletoViewer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author talli
 */
public class MDIBoleto extends javax.swing.JFrame {

    /**
     * Creates new form MDIBoleto
     */
    public MDIBoleto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuFinalizar = new javax.swing.JMenu();
        MenuCedente = new javax.swing.JMenu();
        MenuSacado = new javax.swing.JMenu();
        MenuSacadoAvalista = new javax.swing.JMenu();
        MenuContaBancaria = new javax.swing.JMenu();
        MenuTitulo = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MenuFinalizar.setText("Finalizar");
        MenuFinalizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuFinalizarMouseClicked(evt);
            }
        });
        jMenuBar1.add(MenuFinalizar);

        MenuCedente.setText("Cedente");
        MenuCedente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuCedenteMouseClicked(evt);
            }
        });
        jMenuBar1.add(MenuCedente);

        MenuSacado.setText("Sacado");
        MenuSacado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuSacadoMouseClicked(evt);
            }
        });
        jMenuBar1.add(MenuSacado);

        MenuSacadoAvalista.setText("Sacado Avalista");
        MenuSacadoAvalista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuSacadoAvalistaMouseClicked(evt);
            }
        });
        jMenuBar1.add(MenuSacadoAvalista);

        MenuContaBancaria.setText("Conta Bancaria");
        MenuContaBancaria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuContaBancariaMouseClicked(evt);
            }
        });
        jMenuBar1.add(MenuContaBancaria);

        MenuTitulo.setText("Titulo");
        MenuTitulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuTituloMouseClicked(evt);
            }
        });
        jMenuBar1.add(MenuTitulo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuCedenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuCedenteMouseClicked
        DadosCedente ced = new DadosCedente();
        ced.setVisible(true);
        desktopPane.add(ced);
        
    }//GEN-LAST:event_MenuCedenteMouseClicked

    private void MenuSacadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuSacadoMouseClicked
        DadosdoSacado sac = new DadosdoSacado();
        sac.setVisible(true);
        desktopPane.add(sac);
        
    }//GEN-LAST:event_MenuSacadoMouseClicked

    private void MenuSacadoAvalistaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuSacadoAvalistaMouseClicked
        DadosdoSacadoAvalista saca = new DadosdoSacadoAvalista();
        saca.setVisible(true);
        desktopPane.add(saca);
        
    }//GEN-LAST:event_MenuSacadoAvalistaMouseClicked

    private void MenuContaBancariaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuContaBancariaMouseClicked
        DadosdaContaBancaria conta = new DadosdaContaBancaria();
        conta.setVisible(true);
        desktopPane.add(conta);
        
    }//GEN-LAST:event_MenuContaBancariaMouseClicked

    private void MenuTituloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuTituloMouseClicked
        DadosdoTitulo titu = new DadosdoTitulo();
        titu.setVisible(true);
        desktopPane.add(titu);
    }//GEN-LAST:event_MenuTituloMouseClicked

    private void MenuFinalizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuFinalizarMouseClicked
        
        
        
        
    }//GEN-LAST:event_MenuFinalizarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MDIBoleto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MDIBoleto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MDIBoleto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MDIBoleto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MDIBoleto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuCedente;
    private javax.swing.JMenu MenuContaBancaria;
    private javax.swing.JMenu MenuFinalizar;
    private javax.swing.JMenu MenuSacado;
    private javax.swing.JMenu MenuSacadoAvalista;
    private javax.swing.JMenu MenuTitulo;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables

    
    private static void mostreBoletoNaTela(File arquivoBoleto) {

        java.awt.Desktop desktop = java.awt.Desktop.getDesktop();

        try {
            desktop.open(arquivoBoleto);
        } catch (IOException e) {
            e.printStackTrace();
        }
        
    }
}



